### ISSUE TITLE
Suggestion: split coloration options by DPS type (melee, ranged, caster)

### ISSUE THREAD

**Issue by kaedys** [r00telement/PlayerTags#1]
Frankly love the mod, it's like a much lighter-weight version of JobIcons that still does what I'm after, giving me an at-a-glance color-coded marker of a person's current job.  However, all DPS are currently under a single color, and I can't find a way to make the custom tags do that.  Could you split the DPS tag coloration into melee, ranged, and caster?  People could have it all set to the same color if they wanted, or different if they want to differentiate the types easier.  In particular, I find it helpful to differentiate melee from the other two groups when I'm tanking, so I can better keep an eye on boss facing for positionals and such.

Also, unrelated, would it be possible to color the names using RGB hex codes instead of the block-of-color-squares that is current?  Not sure if the game would make this easy, since that block-of-color-squares appears to be the same one used for nameplate coloration under the existing game options.  But if RGB coloration were an option, that would definitely make the color selection more flexible.

**Comment by r00telement** [comment]
Pretty good idea, will consider this for the next pass I do!

It's not possible to use RGB for the current method that I'm using for nameplate modification, but it may be possible another way, will look into it.

**Comment by r00telement** [comment]
DPS role breakdown is addressed in upcoming 1.1.5.0.
