### ISSUE TITLE
Tags in non-emote chat?

### ISSUE THREAD

**Issue by VariableVixen** [r00telement/PlayerTags#2]
I can't find a way to have tags actually show up in chat. Even custom ones assigned to particular player names, which show up just fine in the nameplates (apparently _with_ the computed ones, which is very nice!), won't show up in chat. The exception is when one of the tagged players is involved in a vanilla emote, as either the target or the performer. Custom emotes and normal messages have no option to display tags.

Is there any plan for allowing tags to be added in custom emotes, the result of `<t>`, `<f>`, etc placeholders, and/or normal chat messages?

**Comment by VariableVixen** [comment]
Update: the target bar(s) also don't show tags - target, focus target, target-of-target. Any plans for those too/either?

**Comment by VariableVixen** [comment]
Interestingly, the placeholders seem to be working now when they weren't earlier, so... ignore that part, I guess. The rest still stands though.

**Comment by r00telement** [comment]
Would like to add tags to other bits of UI where player names appear, will look into that!

Custom tags should always show in chat, role/job tags will only show when the player is in your immediate vicinity. Do let me know if that isn't working correctly.

**Comment by VariableVixen** [comment]
I haven't played since the patch yet (the queues are still murderously long...) but when I made the report, what I was doing was this:

- All players get a computed tag with their class/job abbreviation and role iron, in their nameplate, after their name (works perfectly)
- Specific players _also_ get a static text tag, on nameplate _and_ in chat, _replacing_ their name (works perfectly in nameplates, as the result of a `<t>`/`<f>`/etc placeholder, and when the performer of a vanilla emote - does _not_ work on custom (`/em`) emotes or on normal chat speech)
- As mentioned, no effect on target bar, focus target bar, etc in the game UI

To reproduce, get a friend, set a custom static tag for them, assign it to replace their name in chat, and have them do a vanilla emote, a custom emote, and a normal speech message. Unless I did something wrong with my config, only the first one should show their tag in place of their name.

If you've since updated the plugin then this may be out of date, but like I said, I haven't played since the patch yet.

**Comment by r00telement** [comment]
I followed your steps and was able to see the tag correctly each time.

Try grabbing the latest version if you haven't already and then follow these steps:
1. Disable the plugin.
2. Back up and delete the config file %APPDATA%/XIVLauncher/pluginConfigs/PlayerTags.json.
3. Re-enable the plugin.
4. Add a new custom tag.
5. Set it to replace name in chat.
6. Assign it to someone.
7. Have them perform a "/say test", "/em test", "/dance".
8. Observe the tag shown in chat each time.

If it persists, please send your config here for me to look at.

**Comment by VariableVixen** [comment]
Finally got a chance to test it, and I can confirm that FC chat at least doesn't work. I'm hesitant to post my config because some of the tags are private but I can back it up and then strip the sensitive tags out and post that.

**Comment by VariableVixen** [comment]
Update: I just realised, could the Simple Tweaks feature to recolour names in chat be affecting this? I don't know how either is implemented, but if they both edit the same thing...

**Comment by r00telement** [comment]
It's possible. It might play nicer depending on your plugin load order. I just had a test with the Simple Tweaks option you're referring to and observed a similar problem but not the same as you described:

- When Player Tags has priority (is loaded first), the changes in both plugins display more or less as expected. The custom tag becomes the name, and simple tweaks colors the custom tag.
- When Simple Tweaks has priority, the tags display next to the name instead of replacing it.

Both cases here:
![image](https://user-images.githubusercontent.com/47005506/147503360-17937377-5c9f-496f-af76-c3bd81d96328.png)

You can force Player Tags to have priority by disabling and re-enabling Simple Tweaks, and vice versa.

If you have anything else modifying your chat then that could be a culprit too.
