### ISSUE TITLE
Feature request: Ability to hide Role/Job configuration

### ISSUE THREAD

**Issue by Aida-Enna** [r00telement/PlayerTags#4]
Hello! I saw this plugin today and hoped it would do exactly what it does, and I'm very appreciate of that. Thank you for this! I've been experimenting with addings tags/text to people above their heads to remind me of certain things and it seems to work for that. However, it's a bit of a pain to scroll past all the empty job/role entries to get down to the custom ones, so I was wondering if we could have a toggle to hide the job/role entries (and optionally the custom ones, for people who don't want to use those)?

**Comment by r00telement** [comment]
New UI in 1.1.3.0 should address your concerns, give it a spin!
