### ISSUE TITLE
The plugin stopped working after an update

### ISSUE THREAD

**Issue by shelltar** [r00telement/PlayerTags#5]
After the update, plugin stopped working, I tried resetting the setting, reinstalling deleting plugin and its settings manually from the folder. I can add the tags, but once I try to assign them to people, it immediately unchecks them by itself.

**Comment by holodrum** [comment]
Yeah, it's such an amazing plugin, very helpful to keep track of awesome bards and great people, but it stopped working (in my case) exactly two days ago, exact same behavior as described here.

**Comment by r00telement** [comment]
Thanks for the report, give 1.1.4.0 a go once that's pushed and let me know if it's fixed for you.

**Comment by shelltar** [comment]
It's still not working. Same behavior, whenever I try to add a tag to someone it instantly gets unchecked. I'm on 1.1.4.1.

**Comment by holodrum** [comment]
Mine just updated to 1.1.5.0, and sadly, I'm experiencing the same behavior still.

Hopefully, this can be fixed in the future, this had turned into one of my absolute favorite plugins, tags are useful for so many, not all obvious, things.

**Comment by shelltar** [comment]
@holodrum @r00telement Okay, I figured it out, this property needs to be here, even if empty, to make it work. I originally thought it would be added automatically, or that it's only used to add player names manually. That was my misunderstanding about how it works. 
![image](https://user-images.githubusercontent.com/45462483/147474839-647c0e48-b7d6-432d-89ae-548b09414ff2.png)

**Comment by r00telement** [comment]
Ah right yeah. The value for the option is separate from whether the state is inherited/enabled/disabled. Typically the UX for these options doesn't allow those things to be changed separately, but this particular option can be changed outside of the config editor so the UX is pretty clunky.

I've removed this option in 1.1.6.0 and adding tags via the context menu/quick add tab/tagged players tab should "just work". Give it a try when it gets pushed.

@holodrum fyi

**Comment by holodrum** [comment]
@V3semir Thank you for the tip, I got to test it out right before 1.1.6.0 dropped and it worked as a temporary solution!

@r00telement Everything seems to work exactly as it should now (I'm on 1.1.6.1).
Thank you for your updates with info here and your continuous development on this plugin! :)
